Add PSA manifest files for partition description.
ARMmbed/mbed-os-example-uvisor-thread pull request #77
Opened 2017-10-24 13:46 UTC by romkuz01

This is a prototyping of PSA partition description in XML files
in the current uVisor version.
The current implementation recurcsively searches a given folder for
XML files starting with "box_" prefix which are treated as the manifest
files.
The corresponding code templates are expected to be located in "templates"
folder.
The script that does the job is generate_partition_code.py.

2017-10-24 21:12 UTC, alzix requested changes

2017-10-24 21:12 UTC, alzix commented on generate_partition_code.py
> +        for filename in filenames:
please consider using [fnmatch.filter](https://docs.python.org/2/library/fnmatch.html#fnmatch.filter)
for example:
```python
for root, dirnames, filenames in os.walk(start_dir):
    for filename in fnmatch.filter(filenames, 'box_*.xml'):
```

2017-10-24 21:12 UTC, alzix commented on generate_partition_code.py
> +    return end1 >= start2 and start1 <= end2
i think this condition does not cover all overlap scenarios

2017-10-24 21:12 UTC, alzix commented on generate_partition_code.py
> +    start = 1
i would suggest simplify uniqueness check logic based in the difference between `list` and `set`
for example if the condition `len(your_list) != len(set(your_list))` is not true - then the list has duplicates

2017-10-24 21:12 UTC, alzix commented on generate_partition_code.py
> +    print 'Generating code from "' + manifest['file'] + '" with template "' + box_configuration_template + '".'
please avoid using print function as it is not portable between Python 2 and 3. We will need to support Python 3 eventually.
Please take a look on the [logging framework](https://docs.python.org/2/library/logging.html)

2017-10-24 21:12 UTC, alzix commented on generate_partition_code.py
> +    mmio = mmio.findall('mmioregion') if mmio is not None else []
i would suggest not reusing the same `mmio` variable here but renaming it to `mmioregions`

2017-10-24 21:12 UTC, alzix commented on generate_partition_code.py
> +    for file in src_files:
file is a reserved word in Pyhton - please avoid using it

2017-10-24 21:12 UTC, alzix commented on generate_partition_code.py
> +        src_file_list.append(file.text)
this is a good candidate for list comprehension
`src_file_list  = [x.text for x in src_files]`

2017-10-24 21:12 UTC, alzix commented on generate_partition_code.py
> +        src_file_list.append(file.text)
i think we can validate whether all source files are present at this point.
source files will probably be relative to XML? Otherwise it will be very hard to manage them. Thus all XML files cannot reside in the same templates folder.

2017-10-24 21:12 UTC, alzix commented on generate_partition_code.py
> +        irq_list.append(irq_num)
i think at this point we can check whether all IRQs are valid i think the number is limited to 256?
how does IRQs helps us? Don't we also need handler function pointers per each IRQ? We will have to generate ISR table

2017-10-24 21:12 UTC, alzix commented on generate_partition_code.py
> +        spm_status=manifest['spm_status'] if 'spm_status' in manifest else '',
is there a reason why template keys do not match `manifest` dictionary keys?
in case they would match you would be able just to pass the dict - this will be better from maintenance point of view

2017-10-25 07:10 UTC, romkuz01 commented on generate_partition_code.py
> +    return end1 >= start2 and start1 <= end2
Alex, I'll describe how I came up with this check.
Please follow my logic and try to see if there's an error there.
Let's see when two regions r1 = [s1, e1] and r2 = [s2, e2] DO NOT overlap.
This happens either when r1 precedes r2 (happens when e1 < s2) or
when r1 follows r2 (happens when s1 > e2).
So, this is a check for two regions not overlapping:
e1 < s2 or s1 > e2.
A check for overlapping is NOT of this check: < turns into >=, > turns into <=, or turns into and:
e1 >= s2 and s1 <= e2
Looks like it covers all the cases.

2017-10-25 08:13 UTC, romkuz01 commented on generate_partition_code.py
> +        irq_list.append(irq_num)
The number is not limited by 256, I think the architecture let's us have up to 512 -16 IRQs.
The real systems usually implement less.
I thought about checking for the upper limit but currently decided to drop this check due to the number of IRQs not being constant for different platforms.

Probably we do need to supply handler functions. I'll check and modify DTD accordingly.

2017-10-25 08:38 UTC, romkuz01 commented on generate_partition_code.py
> +        for filename in filenames:
Accepted, changed the code to use fnmatch.

2017-10-25 08:41 UTC, romkuz01 commented on generate_partition_code.py
> +    mmio = mmio.findall('mmioregion') if mmio is not None else []
Accepted.

2017-10-25 08:42 UTC, romkuz01 commented on generate_partition_code.py
> +    for file in src_files:
Renamed to src_file.

2017-10-25 09:02 UTC, romkuz01 commented on generate_partition_code.py
> +        src_file_list.append(file.text)
1)Changed to src_file_list = [src_file.text for src_file in src_files]
2) Added source file existence check. The path in XML file is now relative to XML location:
<filename>../source/led1.cpp</filename>
thus XML files still can be in the same folder.

2017-10-25 09:17 UTC, romkuz01 commented on generate_partition_code.py
> +    start = 1
This will catch an error, but won't say which element is duplicated.
Since we want the script to produce informative error messages to allow easy and fast fixes I'm leaving the code as is.

2017-10-25 09:26 UTC, romkuz01 commented on generate_partition_code.py
> +    print 'Generating code from "' + manifest['file'] + '" with template "' + box_configuration_template + '".'
Actually this is a debug leftover I forgot to remove.
I'll erase this line.

2017-10-26 20:11 UTC, mikisch81 requested changes
1. The prints are better understood as formatted strings.
   So instead of:
   ```
   raise ValueError('Source file "' + src_file + '" mentioned in "' + manifest_file + '" can\'t be found at "' + src_file_path + '"."')
   ```
   You can write:
   ```
   raise ValueError("Source file %s mentioned in %s can't be found at %s." % (src_file, manifest_file, src_file_path))
   ```
1. I think `assert condition, 'text'` is better to use than
    ```
    if cond:
        DO_SOMETHING
    else:
        raise SomeError, 'text'
    ```
    Same effect with 4 times less code
1. Consider using the [logging](https://docs.python.org/2/library/logging.html) module, there are many examples of it in TZInfra code (like postbuild).

2017-10-26 20:11 UTC, mikisch81 commented on generate_partition_code.py
> +def to_number(num_str, error_message=None):
This entire function is redundant.
`int(num, base)` asserts with a **ValueError** if the number is not a legal number of the given base.

2017-10-26 20:11 UTC, mikisch81 commented on generate_partition_code.py
> +        'stack_size': to_number(stack_size_str,
You can assert the value here using `assert`, I think that stack size can be either decimal or hexadecimal (`0x1000` or `4096` should be both accepted).
```
assert int(stack_size_str, 10) or int(stack_size_str, 16), 'Stack size in %s must be a decimal/hexadecimal number, %s given' % (manifest_file, stack_size_str)
```

2017-10-26 20:11 UTC, mikisch81 commented on generate_partition_code.py
> +        'heap_size': to_number(heap_size_str,
same as `stack_size`

2017-10-26 20:11 UTC, mikisch81 commented on generate_partition_code.py
> +    if len(mmio_region_list) > 0:
```
if mmio_region_list:
    partition['mmio_regions'] = mmio_region_list
```
has the same effect.

2017-10-26 20:11 UTC, mikisch81 commented on generate_partition_code.py
> +def region_overlap(region1, region2):
Who uses this function?

2017-10-26 20:11 UTC, mikisch81 commented on generate_partition_code.py
> +    for manifest in manifests:
Since you just check here that all the external SFIDs of a given partitions are defined in the other partitions you can reduce the entire block to something like:
```
orphand_sfids = set(manifest['extern_sfids']) - set(sfids)
for sfid in orphand_sfids:
    error 'External SFID %s required by %s is not declared in any partition' % (sfid, manifest['file'])
```
This takes all the sfids in the 1st list that are not in the 2nd list (a cast to `set` is needed in order to use the `-` sign).

2017-10-26 20:11 UTC, mikisch81 commented on generate_partition_code.py
> +    parser.add_argument(
Existence of the workspace directory should be verified by the parser.
See TZInfra postbuild script for examples.

2017-10-26 20:11 UTC, mikisch81 commented on generate_partition_code.py
> +    parser.add_argument(
Do the output dir needs to exist?
If so than same as with the workspace dir.
Else need to create a new dir or overwrite if exist.

2017-10-26 20:11 UTC, mikisch81 commented on templates/common_configuration.tpl
> +    ({{region_pair['region1']['base']}} + {{region_pair['region1']['size']}} - 1 < {{region_pair['region2']['base']}}) ||
Should it be `&&` between the conditions?
`static_assert(1_not_overlap_2 && 2_not_overlap_1)`

2017-10-29 08:42 UTC, romkuz01 commented on generate_partition_code.py
> +def region_overlap(region1, region2):
You're right. It's no longer used.
Was used before when I did overlap checks in the script itself and not in the generated static asserts.

2017-10-29 09:55 UTC, romkuz01 commented on generate_partition_code.py
> +    if len(mmio_region_list) > 0:
Changed len(..) > 0 checks as suggested.

2017-10-29 11:30 UTC, romkuz01 commented on templates/common_configuration.tpl
> +    ({{region_pair['region1']['base']}} + {{region_pair['region1']['size']}} - 1 < {{region_pair['region2']['base']}}) ||
We agreed it should be ||.

2017-10-29 11:31 UTC, romkuz01 commented on generate_partition_code.py
> +    for manifest in manifests:
Changed the code in a similar way.

2017-10-29 14:52 UTC, romkuz01 commented on generate_partition_code.py
> +    parser.add_argument(
Added TZInfra's argparse_action_helper.py script to support this logic.

2017-12-12 14:24 UTC, closed without merging